---
# Variable configuration.
- include_tasks: variables.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL single node or galera first node.
- include_tasks: deploy.yml

- name: Stop mariadb on first mariadb Galera cluster node
  service: name=mariadb state=stopped
  when: galera_cluster

- include_tasks: cluster-bootstrap.yml
  when: galera_cluster and (inventory_hostname == galera_master)

- name: Restart the other MariaDB Galera cluster nodes
  service: name=mariadb state=restarted
  when: galera_cluster and (inventory_hostname != galera_master)
